### ISSUE TITLE
Doesn't set cookies for the target domain

### ISSUE THREAD

**Issue by lexanth** [avaneeshtripathi/copy-cookie#1]
I'm trying to copy from <real https URL> to `https://localhost:3000`, but the cookies aren't coming across.

https://github.com/avaneeshtripathi/copy-cookie/blob/master/popup.js#L57-L58

This gets the domain from the input, but as far as I can see it doesn't do anything with it - it just reads the cookies from `tab[0].url` and sets them back on `tab[0].url`. Looks a trivial fix?

**Comment by avaneeshtripathi** [comment]
Hey!
Sorry, for being this late. By now you must have already worked it out. The extension published on the web store is in a working state whereas master was broken as i was playing around a bit and messed it all up. Didn't get time to fix.

It's been fixed now bdw and you can take the latest master. It should show version 2.0.0 which i am going to publish.
